export const questionTypes = {
  GET_QUESTION: 'GET_QUESTION',
  GET_QUESTION_SUCCESS: 'GET_QUESTION_SUCCESS',
  QUESTION_ERROR: 'QUESTION_ERROR',
  CREATE_QUESTION: 'CREATE_QUESTION',
  DELETE_QUESTION: 'DELETE_QUESTION',
};
