export const questionTypes = {
  GET_QUESTION: 'GET_QUESTION',
  GET_QUESTION_SUCCESS: 'GET_QUESTION_SUCCESS',
  GET_QUESTION_FAILURE: 'GET_QUESTION_FAILURE',
  GET_QUESTION_SINGLE: 'GET_QUESTION_SINGLE',
  GET_QUESTION_SINGLE_SUCCESS: 'GET_QUESTION_SINGLE_SUCCESS',
  GET_QUESTION_SINGLE_FAILURE: 'GET_QUESTION_SINGLE_FAILURE',
  QUESTION_ERROR: 'QUESTION_ERROR',
  CREATE_QUESTION: 'CREATE_QUESTION',
  DELETE_QUESTION: 'DELETE_QUESTION',
};
